const LINKS = {
  Login: "/auth/login",
  SignUp: "/auth/registerseller",
  selectregister: "/auth/selectregister",
  CollectorSignUp: "/auth/registercollector",
  forgotpassword: "/auth/forgot-password",
  verifyOTP: "/auth/verify-otp",
  verifyEmail: "/auth/verify-email",
  contactus: "/contactus",
  Home: "/",
  Usefulinfo:"/usefulinfo",
  Allsellers: "/sellers",
  Allitems: "/items",
  sellerProfile: "/seller/profile",
  AddItems: "/seller/additems",
  collectorProfile: "/collector/profile",
  editProfile: "/edit-profile",
  editCollection: "/seller/editcollection",
  createCollection: "/seller/createcollection",
  allSellerItemsPublic: "/allpublicselleritems",
  allSellerItemsPrivate: "/seller/allprivateselleritems",
  showColletion: "/showcollectionpage",
  singleCollectionpublic: "/singleCollection",
  singleCollectionPrivate: "/seller/singlecollectionprivate",
  chatpage: "/chat",
  hidden: "/seller/hidden",
  adminDashboard: "/admindashboard",
  featured: "/seller/featured",
  adminInformation: "/admininformation",
  admininformationtext: "/admininformation/text",
  changepass:"/changepass",
  accountVisibility:"/accountvisibility",
  disclaimer:"/disclaimer",
blockuser:"/block"
};

export default LINKS